apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quick-tunnel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: mini-paas-cloud
  source:
    repoURL: https://github.com/devanshlamba/mini-paas.git
    targetRevision: main
    path: deploy/platform/quick-tunnel
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  revisionHistoryLimit: 10
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
